spring:
  application:
    name: mcp-distributed-client
  main:
    web-application-type: none
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications


    alibaba:
      mcp:
        nacos:
          client:
            enabled: true
            streamable:
              connections:
                server1:
                  service-name: webflux-mcp-server
                  version: 1.0.0
            sse:
              connections:
                server1:
                  service-name: webflux-sse-mcp-server
                  version: 1.0.0
            configs:
              server1:
                namespace: example_test
                serverAddr: 127.0.0.1:8848
                username: nacos
                password: nacos
