server:
  port: 21001

spring:
  main:
    banner-mode: off
  application:
    name: mcp-nacos-register-extensions-sse-example
  ai:
    mcp:
      server:
        name: webflux-sse-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        protocol: sse
        request-timeout: 20s
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
          disallow-delete: false

    alibaba:
      mcp:
        nacos:
          namespace: example_test
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          register:
            enabled: true
            service-group: mcp-server       ## 指定分组名称
            service-name: webflux-sse-mcp-server ## 指定服务名称
