server:
  port: 19000

spring:
  application:
    name: mcp-gateway-server
  ai:
    mcp:
      server:
        name: mcp-nacos-gateway-example
        version: 1.0.0
        enabled: true
        protocol: sse
        type: async
        instructions: "Nacos MCP Gateway - 聚合多个 MCP Server 的工具网关"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false
    dashscope:
      api-key: sk-51f53a871d434863880761b4d96b913c

    alibaba:
      # MCP Gateway 配置
      mcp:
        gateway:
          enabled: true
          registry: nacos
          # 配置要发现和聚合的 MCP Server 服务名称
          nacos:
            serviceNames:
              - webflux-sse-mcp-server         # SSE 协议的 MCP Server
              - webflux-mcp-server  # Streamable 协议的 MCP Server
#              - feedback-mcp-server
        # Nacos 注册中心配置
        nacos:
          server-addr: 172.22.26.59:8848,172.22.26.59:8858,172.22.26.59:8868
          namespace: example_test
          username: nacos
          password: nacos
          register:
            enabled: true

logging:
  level:
    com.alibaba.cloud.ai.mcp: DEBUG
